package org.smartloli.kafka.eagle.web.pojo;

import java.util.Date;

public class KeConfigure {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.configureId
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private String configureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.configureName
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private String configurename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.age
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.gender
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.disease
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private String disease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.metric
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private String metric;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.dateBegin
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private Date datebegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.dateEnd
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private Date dateend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.slidingWindowSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private Integer slidingwindowsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.paaSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private Integer paasize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.alphabetSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private Integer alphabetsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.analysisWindowStartSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private Integer analysiswindowstartsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.frequencyThreshold
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private Integer frequencythreshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.rThreshold
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private Integer rthreshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.k
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private Integer k;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_configure.isDone
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    private String isdone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.configureId
     *
     * @return the value of ke_configure.configureId
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public String getConfigureid() {
        return configureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.configureId
     *
     * @param configureid the value for ke_configure.configureId
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setConfigureid(String configureid) {
        this.configureid = configureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.configureName
     *
     * @return the value of ke_configure.configureName
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public String getConfigurename() {
        return configurename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.configureName
     *
     * @param configurename the value for ke_configure.configureName
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setConfigurename(String configurename) {
        this.configurename = configurename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.age
     *
     * @return the value of ke_configure.age
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.age
     *
     * @param age the value for ke_configure.age
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.gender
     *
     * @return the value of ke_configure.gender
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.gender
     *
     * @param gender the value for ke_configure.gender
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.disease
     *
     * @return the value of ke_configure.disease
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public String getDisease() {
        return disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.disease
     *
     * @param disease the value for ke_configure.disease
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setDisease(String disease) {
        this.disease = disease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.metric
     *
     * @return the value of ke_configure.metric
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public String getMetric() {
        return metric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.metric
     *
     * @param metric the value for ke_configure.metric
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setMetric(String metric) {
        this.metric = metric;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.dateBegin
     *
     * @return the value of ke_configure.dateBegin
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public Date getDatebegin() {
        return datebegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.dateBegin
     *
     * @param datebegin the value for ke_configure.dateBegin
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setDatebegin(Date datebegin) {
        this.datebegin = datebegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.dateEnd
     *
     * @return the value of ke_configure.dateEnd
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public Date getDateend() {
        return dateend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.dateEnd
     *
     * @param dateend the value for ke_configure.dateEnd
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setDateend(Date dateend) {
        this.dateend = dateend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.slidingWindowSize
     *
     * @return the value of ke_configure.slidingWindowSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public Integer getSlidingwindowsize() {
        return slidingwindowsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.slidingWindowSize
     *
     * @param slidingwindowsize the value for ke_configure.slidingWindowSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setSlidingwindowsize(Integer slidingwindowsize) {
        this.slidingwindowsize = slidingwindowsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.paaSize
     *
     * @return the value of ke_configure.paaSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public Integer getPaasize() {
        return paasize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.paaSize
     *
     * @param paasize the value for ke_configure.paaSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setPaasize(Integer paasize) {
        this.paasize = paasize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.alphabetSize
     *
     * @return the value of ke_configure.alphabetSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public Integer getAlphabetsize() {
        return alphabetsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.alphabetSize
     *
     * @param alphabetsize the value for ke_configure.alphabetSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setAlphabetsize(Integer alphabetsize) {
        this.alphabetsize = alphabetsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.analysisWindowStartSize
     *
     * @return the value of ke_configure.analysisWindowStartSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public Integer getAnalysiswindowstartsize() {
        return analysiswindowstartsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.analysisWindowStartSize
     *
     * @param analysiswindowstartsize the value for ke_configure.analysisWindowStartSize
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setAnalysiswindowstartsize(Integer analysiswindowstartsize) {
        this.analysiswindowstartsize = analysiswindowstartsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.frequencyThreshold
     *
     * @return the value of ke_configure.frequencyThreshold
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public Integer getFrequencythreshold() {
        return frequencythreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.frequencyThreshold
     *
     * @param frequencythreshold the value for ke_configure.frequencyThreshold
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setFrequencythreshold(Integer frequencythreshold) {
        this.frequencythreshold = frequencythreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.rThreshold
     *
     * @return the value of ke_configure.rThreshold
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public Integer getRthreshold() {
        return rthreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.rThreshold
     *
     * @param rthreshold the value for ke_configure.rThreshold
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setRthreshold(Integer rthreshold) {
        this.rthreshold = rthreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.k
     *
     * @return the value of ke_configure.k
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public Integer getK() {
        return k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.k
     *
     * @param k the value for ke_configure.k
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setK(Integer k) {
        this.k = k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_configure.isDone
     *
     * @return the value of ke_configure.isDone
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public String getIsdone() {
        return isdone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_configure.isDone
     *
     * @param isdone the value for ke_configure.isDone
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    public void setIsdone(String isdone) {
        this.isdone = isdone;
    }

    @Override
    public String toString() {
        return "KeConfigure{" +
                "configureid='" + configureid + '\'' +
                ", configurename='" + configurename + '\'' +
                ", age='" + age + '\'' +
                ", gender='" + gender + '\'' +
                ", disease='" + disease + '\'' +
                ", metric='" + metric + '\'' +
                ", datebegin=" + datebegin +
                ", dateend=" + dateend +
                ", slidingwindowsize=" + slidingwindowsize +
                ", paasize=" + paasize +
                ", alphabetsize=" + alphabetsize +
                ", analysiswindowstartsize=" + analysiswindowstartsize +
                ", frequencythreshold=" + frequencythreshold +
                ", rthreshold=" + rthreshold +
                ", k=" + k +
                ", isdone='" + isdone + '\'' +
                '}';
    }
}
