package org.smartloli.kafka.eagle.web.pojo;

public class KePatternDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_pattern_detail.id
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_pattern_detail.symbolicPatternId
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    private String symbolicpatternid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_pattern_detail.measureName
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    private String measurename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_pattern_detail.measureValue
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    private String measurevalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_pattern_detail.id
     *
     * @return the value of ke_pattern_detail.id
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_pattern_detail.id
     *
     * @param id the value for ke_pattern_detail.id
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_pattern_detail.symbolicPatternId
     *
     * @return the value of ke_pattern_detail.symbolicPatternId
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    public String getSymbolicpatternid() {
        return symbolicpatternid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_pattern_detail.symbolicPatternId
     *
     * @param symbolicpatternid the value for ke_pattern_detail.symbolicPatternId
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    public void setSymbolicpatternid(String symbolicpatternid) {
        this.symbolicpatternid = symbolicpatternid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_pattern_detail.measureName
     *
     * @return the value of ke_pattern_detail.measureName
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    public String getMeasurename() {
        return measurename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_pattern_detail.measureName
     *
     * @param measurename the value for ke_pattern_detail.measureName
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    public void setMeasurename(String measurename) {
        this.measurename = measurename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_pattern_detail.measureValue
     *
     * @return the value of ke_pattern_detail.measureValue
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    public String getMeasurevalue() {
        return measurevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_pattern_detail.measureValue
     *
     * @param measurevalue the value for ke_pattern_detail.measureValue
     *
     * @mbggenerated Wed May 09 12:04:41 CST 2018
     */
    public void setMeasurevalue(String measurevalue) {
        this.measurevalue = measurevalue;
    }
}