package org.smartloli.kafka.eagle.web.pojo;

public class KeSymbolicPattern {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_symbolic_pattern.id
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_symbolic_pattern.configureId
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    private String configureid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_symbolic_pattern.alias
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_symbolic_pattern.order
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    private Integer patternOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ke_symbolic_pattern.length
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    private Integer length;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_symbolic_pattern.id
     *
     * @return the value of ke_symbolic_pattern.id
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_symbolic_pattern.id
     *
     * @param id the value for ke_symbolic_pattern.id
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_symbolic_pattern.configureId
     *
     * @return the value of ke_symbolic_pattern.configureId
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    public String getConfigureid() {
        return configureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_symbolic_pattern.configureId
     *
     * @param configureid the value for ke_symbolic_pattern.configureId
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    public void setConfigureid(String configureid) {
        this.configureid = configureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_symbolic_pattern.alias
     *
     * @return the value of ke_symbolic_pattern.alias
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_symbolic_pattern.alias
     *
     * @param alias the value for ke_symbolic_pattern.alias
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    public Integer getPatternOrder() {
        return patternOrder;
    }

    public void setPatternOrder(Integer patternOrder) {
        this.patternOrder = patternOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ke_symbolic_pattern.length
     *
     * @return the value of ke_symbolic_pattern.length
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ke_symbolic_pattern.length
     *
     * @param length the value for ke_symbolic_pattern.length
     *
     * @mbggenerated Wed May 09 12:07:25 CST 2018
     */
    public void setLength(Integer length) {
        this.length = length;
    }
}
