package org.smartloli.kafka.eagle.web.dao;

import org.smartloli.kafka.eagle.web.pojo.KeConfigure;

public interface KeConfigureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ke_configure
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    int deleteByPrimaryKey(String configureid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ke_configure
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    int insert(KeConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ke_configure
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    int insertSelective(KeConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ke_configure
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    KeConfigure selectByPrimaryKey(String configureid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ke_configure
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    int updateByPrimaryKeySelective(KeConfigure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ke_configure
     *
     * @mbggenerated Wed May 09 10:35:34 CST 2018
     */
    int updateByPrimaryKey(KeConfigure record);
}